// This file is auto-generated by @hey-api/openapi-ts

/**
 * AbilityTreeNode
 */
export type AbilityTreeNode = {
    /**
     * Node Type
     */
    node_type: 'ability' | 'connector';
    /**
     * Name
     */
    name: string;
    /**
     * Pretty Name
     */
    pretty_name: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Connector Type
     */
    connector_type: 'connector_down_left' | 'connector_right_down' | 'connector_right_down_left' | 'connector_right_left' | 'connector_up_down' | 'connector_up_down_left' | 'connector_up_right_down' | 'connector_up_right_down_left' | 'connector_up_right_left' | null;
    /**
     * X
     */
    x: number;
    /**
     * Y
     */
    y: number;
    /**
     * Unlocked
     */
    unlocked: boolean;
    /**
     * Node Id
     */
    node_id: string;
    /**
     * Icon Id
     */
    icon_id: string;
    /**
     * Icon Url
     */
    icon_url: string;
};

/**
 * AbilityTreePage
 */
export type AbilityTreePage = {
    /**
     * Page Number
     */
    page_number: number;
    /**
     * Nodes
     */
    nodes: Array<AbilityTreeNode>;
};

/**
 * BedwarsMode
 */
export type BedwarsMode = {
    /**
     * Games Played
     */
    games_played: number;
    /**
     * Winstreak
     */
    winstreak: number;
    /**
     * Wins
     */
    wins: number;
    /**
     * Losses
     */
    losses: number;
    /**
     * Winn Loss Ratio
     */
    winn_loss_ratio: number;
    /**
     * Kills
     */
    kills: number;
    /**
     * Deaths
     */
    deaths: number;
    /**
     * Kill Death Ratio
     */
    kill_death_ratio: number;
    /**
     * Final Kills
     */
    final_kills: number;
    /**
     * Final Deaths
     */
    final_deaths: number;
    /**
     * Final Kill Death Ratio
     */
    final_kill_death_ratio: number;
    /**
     * Beds Broken
     */
    beds_broken: number;
    /**
     * Beds Lost
     */
    beds_lost: number;
    /**
     * Bed Broken Lost Ratio
     */
    bed_broken_lost_ratio: number;
    /**
     * Items Purchased
     */
    items_purchased: number;
    /**
     * Resources Collected
     */
    resources_collected: number;
    /**
     * Iron Collected
     */
    iron_collected: number;
    /**
     * Gold Collected
     */
    gold_collected: number;
    /**
     * Diamonds Collected
     */
    diamonds_collected: number;
    /**
     * Emeralds Collected
     */
    emeralds_collected: number;
};

/**
 * BedwarsProfile
 */
export type BedwarsProfile = {
    /**
     * Experience
     */
    experience: number;
    /**
     * Level
     */
    level: number;
    /**
     * Tokens
     */
    tokens: number;
    overall_stats: BedwarsMode;
    solo_stats: BedwarsMode;
    duo_stats: BedwarsMode;
    trio_stats: BedwarsMode;
    quad_stats: BedwarsMode;
};

/**
 * CapeImageData
 */
export type CapeImageData = {
    /**
     * Front B64
     */
    front_b64: string;
    /**
     * Back B64
     */
    back_b64: string;
};

/**
 * ContentProgress
 */
export type ContentProgress = {
    /**
     * Total
     */
    total: number | null;
    /**
     * List
     */
    list: {
        [key: string]: number;
    };
};

/**
 * DonutPlayerStats
 */
export type DonutPlayerStats = {
    /**
     * Money
     */
    money: number;
    /**
     * Shards
     */
    shards: number;
    /**
     * Kills
     */
    kills: number;
    /**
     * Deaths
     */
    deaths: number;
    /**
     * Playtime Hours
     */
    playtime_hours: number;
    /**
     * Placed Blocks
     */
    placed_blocks: number;
    /**
     * Broken Blocks
     */
    broken_blocks: number;
    /**
     * Mobs Killed
     */
    mobs_killed: number;
    /**
     * Money Spent
     */
    money_spent: number;
    /**
     * Money Earned
     */
    money_earned: number;
    /**
     * Online
     */
    online: boolean;
};

/**
 * DungeonCompletions
 */
export type DungeonCompletions = {
    /**
     * Name
     */
    name: string;
    /**
     * Normal Completions
     */
    normal_completions: number | null;
    /**
     * Corrupted Completions
     */
    corrupted_completions: number | null;
};

/**
 * DungeonProgress
 */
export type DungeonProgress = {
    /**
     * Total
     */
    total: number | null;
    /**
     * List
     */
    list: Array<DungeonCompletions>;
};

/**
 * ErrorResponse
 */
export type ErrorResponse = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HistogramData
 */
export type HistogramData = {
    /**
     * Metric Key
     */
    metric_key: string;
    /**
     * Unit
     */
    unit: string | null;
    /**
     * Higher Is Better
     */
    higher_is_better: boolean;
    /**
     * Player Value
     */
    player_value: number;
    /**
     * Sample Size
     */
    sample_size: number;
    /**
     * Min Value
     */
    min_value: number;
    /**
     * Max Value
     */
    max_value: number;
    /**
     * Buckets
     */
    buckets: Array<number>;
    /**
     * Counts
     */
    counts: Array<number>;
    /**
     * Percentile
     */
    percentile: number;
};

/**
 * HypixelFullData
 */
export type HypixelFullData = {
    player: HypixelPlayer;
    guild: HypixelGuild | null;
};

/**
 * HypixelGuild
 */
export type HypixelGuild = {
    /**
     * Source
     */
    source: string;
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Created
     */
    created: string;
    /**
     * Experience
     */
    experience: number;
    /**
     * Tag
     */
    tag: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Publicly Listed
     */
    publicly_listed: boolean;
    /**
     * Members
     */
    members: Array<HypixelGuildMember>;
};

/**
 * HypixelGuildMember
 */
export type HypixelGuildMember = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Rank
     */
    rank: string;
    /**
     * Joined
     */
    joined: string;
};

/**
 * HypixelGuildMemberFull
 */
export type HypixelGuildMemberFull = {
    /**
     * Username
     */
    username: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Rank
     */
    rank: string;
    /**
     * Joined
     */
    joined: string;
    /**
     * Skin Showcase B64
     */
    skin_showcase_b64: string;
};

/**
 * HypixelPlayer
 */
export type HypixelPlayer = {
    /**
     * Source
     */
    source: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * First Login
     */
    first_login: string | null;
    /**
     * Last Login
     */
    last_login: string | null;
    /**
     * Rank
     */
    rank: string | null;
    /**
     * Achievement Points
     */
    achievement_points: number;
    /**
     * Network Experience
     */
    network_experience: number;
    /**
     * Network Level
     */
    network_level: number;
    /**
     * Karma
     */
    karma: number;
    bedwars: BedwarsProfile;
};

/**
 * MCCIFriend
 */
export type McciFriend = {
    /**
     * Username
     */
    username: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Rank
     */
    rank: string | null;
};

/**
 * MCCIPlayer
 */
export type McciPlayer = {
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Username
     */
    username: string | null;
    /**
     * Rank
     */
    rank: string | null;
    /**
     * Online
     */
    online: boolean;
    /**
     * First Join
     */
    first_join: string | null;
    /**
     * Last Join
     */
    last_join: string | null;
    /**
     * Friends
     */
    friends: Array<McciFriend>;
    stats: McciStats | null;
    /**
     * Plus Subscribed
     */
    plus_subscribed: boolean;
};

/**
 * MCCIStats
 */
export type McciStats = {
    /**
     * Coins
     */
    coins: number | null;
    /**
     * Royal Reputation
     */
    royal_reputation: number | null;
    /**
     * Anglr Token
     */
    anglr_token: number | null;
    /**
     * Trophies
     */
    trophies: number | null;
    /**
     * Max Trophies
     */
    max_trophies: number | null;
    /**
     * Level
     */
    level: number | null;
    /**
     * Level Evolution
     */
    level_evolution: number | null;
};

/**
 * MojangData
 */
export type MojangData = {
    /**
     * Source
     */
    source: string;
    /**
     * Username
     */
    username: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Has Cape
     */
    has_cape: boolean;
    /**
     * Cape Name
     */
    cape_name: string | null;
    /**
     * Skin Url
     */
    skin_url: string;
    /**
     * Cape Url
     */
    cape_url: string | null;
    /**
     * Skin Showcase B64
     */
    skin_showcase_b64: string;
    /**
     * Cape Front B64
     */
    cape_front_b64: string | null;
    /**
     * Cape Back B64
     */
    cape_back_b64: string | null;
};

/**
 * PlayerRestrictions
 */
export type PlayerRestrictions = {
    /**
     * Main Access
     */
    main_access: boolean;
    /**
     * Character Data Access
     */
    character_data_access: boolean;
    /**
     * Character Build Access
     */
    character_build_access: boolean;
    /**
     * Online Status
     */
    online_status: boolean;
};

/**
 * PlayerStatus
 */
export type PlayerStatus = {
    /**
     * Wynncraft Restricted
     */
    wynncraft_restricted: boolean;
    /**
     * Wynncraft Online
     */
    wynncraft_online: boolean;
    /**
     * Wynncraft Server
     */
    wynncraft_server: string | null;
    /**
     * Wynncraft Character
     */
    wynncraft_character: string | null;
    /**
     * Hypixel Online
     */
    hypixel_online: boolean;
    /**
     * Hypixel Game Type
     */
    hypixel_game_type: string | null;
    /**
     * Hypixel Mode
     */
    hypixel_mode: string | null;
};

/**
 * ProfessionInfo
 */
export type ProfessionInfo = {
    /**
     * Fishing
     */
    fishing: number;
    /**
     * Woodcutting
     */
    woodcutting: number;
    /**
     * Mining
     */
    mining: number;
    /**
     * Farming
     */
    farming: number;
    /**
     * Scribing
     */
    scribing: number;
    /**
     * Jeweling
     */
    jeweling: number;
    /**
     * Alchemism
     */
    alchemism: number;
    /**
     * Cooking
     */
    cooking: number;
    /**
     * Weaponsmithing
     */
    weaponsmithing: number;
    /**
     * Tailoring
     */
    tailoring: number;
    /**
     * Woodworking
     */
    woodworking: number;
    /**
     * Armouring
     */
    armouring: number;
};

/**
 * Storyline
 */
export type Storyline = {
    /**
     * Name
     */
    name: string;
    /**
     * Quests Completed
     */
    quests_completed: number;
    /**
     * Quests Available
     */
    quests_available: number;
    /**
     * Quests
     */
    quests: Array<StorylineQuest>;
};

/**
 * StorylineQuest
 */
export type StorylineQuest = {
    /**
     * Name
     */
    name: string;
    /**
     * Completed
     */
    completed: boolean;
};

/**
 * UserCapeData
 */
export type UserCapeData = {
    /**
     * Name
     */
    name: string;
    /**
     * Url
     */
    url: string;
    images: CapeImageData;
    /**
     * Removed
     */
    removed: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WynncraftCharacterContent
 */
export type WynncraftCharacterContent = {
    /**
     * Content Completed
     */
    content_completed: number | null;
    /**
     * Quests Completed
     */
    quests_completed: number | null;
    /**
     * Discoveries
     */
    discoveries: number | null;
    /**
     * Caves
     */
    caves: number | null;
    /**
     * Lootruns
     */
    lootruns: number | null;
    /**
     * World Events
     */
    world_events: number | null;
    /**
     * Wars
     */
    wars: number | null;
    dungeons: DungeonProgress;
    raids: ContentProgress;
    /**
     * Storylines
     */
    storylines: Array<Storyline> | null;
};

/**
 * WynncraftCharacterInfo
 */
export type WynncraftCharacterInfo = {
    /**
     * Character Uuid
     */
    character_uuid: string;
    /**
     * Character Class
     */
    character_class: string;
    /**
     * Nickname
     */
    nickname: string | null;
    /**
     * Reskin
     */
    reskin: string | null;
    /**
     * Level
     */
    level: number;
    /**
     * Playtime
     */
    playtime: number | null;
    /**
     * Gamemodes
     */
    gamemodes: Array<string>;
    professions: ProfessionInfo | null;
    skill_points: WynncraftCharacterSkillPoints | null;
    content: WynncraftCharacterContent;
    stats: WynncraftCharacterStats;
    /**
     * Removed Stats
     */
    removed_stats: Array<string>;
};

/**
 * WynncraftCharacterSkillPoints
 */
export type WynncraftCharacterSkillPoints = {
    /**
     * Strength
     */
    strength: number;
    /**
     * Dexterity
     */
    dexterity: number;
    /**
     * Intelligence
     */
    intelligence: number;
    /**
     * Defense
     */
    defense: number;
    /**
     * Agility
     */
    agility: number;
};

/**
 * WynncraftCharacterStats
 */
export type WynncraftCharacterStats = {
    /**
     * Mobs Killed
     */
    mobs_killed: number | null;
    /**
     * Chests Opened
     */
    chests_opened: number | null;
    /**
     * Blocks Walked
     */
    blocks_walked: number | null;
    /**
     * Logins
     */
    logins: number | null;
    /**
     * Deaths
     */
    deaths: number | null;
};

/**
 * WynncraftGuildInfo
 */
export type WynncraftGuildInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Prefix
     */
    prefix: string;
    /**
     * Guild Uuid
     */
    guild_uuid: string;
    /**
     * Level
     */
    level: number;
    /**
     * Wars
     */
    wars: number;
    /**
     * Territories
     */
    territories: number;
    /**
     * Created
     */
    created: string;
    /**
     * Member Count
     */
    member_count: number;
    /**
     * Members
     */
    members: Array<WynncraftGuildMember>;
};

/**
 * WynncraftGuildMember
 */
export type WynncraftGuildMember = {
    /**
     * Username
     */
    username: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Online
     */
    online: boolean;
    /**
     * Joined
     */
    joined: string;
    /**
     * Rank
     */
    rank: string;
};

/**
 * WynncraftPlayerStats
 */
export type WynncraftPlayerStats = {
    /**
     * Wars
     */
    wars: number;
    /**
     * Mobs Killed
     */
    mobs_killed: number;
    /**
     * Chests Opened
     */
    chests_opened: number;
    /**
     * Dungeons Completed
     */
    dungeons_completed: number;
    /**
     * Raids Completed
     */
    raids_completed: number;
    /**
     * Playtime Hours
     */
    playtime_hours: number;
};

/**
 * WynncraftPlayerSummary
 */
export type WynncraftPlayerSummary = {
    /**
     * Username
     */
    username: string;
    /**
     * Uuid
     */
    uuid: string;
    /**
     * Online
     */
    online: boolean;
    /**
     * Rank
     */
    rank: string;
    /**
     * Rank Badge
     */
    rank_badge: string | null;
    /**
     * First Login
     */
    first_login: string | null;
    /**
     * Last Login
     */
    last_login: string | null;
    /**
     * Guild Name
     */
    guild_name: string | null;
    /**
     * Guild Prefix
     */
    guild_prefix: string | null;
    player_stats: WynncraftPlayerStats | null;
    /**
     * Characters
     */
    characters: Array<WynncraftCharacterInfo>;
    restrictions: PlayerRestrictions;
};

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type HealthCheckHealthzGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthCheckHealthzGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetMojangProfileV1PlayersMojangIdentifierGetData = {
    body?: never;
    path: {
        /**
         * Identifier
         */
        identifier: unknown;
    };
    query?: never;
    url: '/v1/players/mojang/{identifier}';
};

export type GetMojangProfileV1PlayersMojangIdentifierGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetMojangProfileV1PlayersMojangIdentifierGetError = GetMojangProfileV1PlayersMojangIdentifierGetErrors[keyof GetMojangProfileV1PlayersMojangIdentifierGetErrors];

export type GetMojangProfileV1PlayersMojangIdentifierGetResponses = {
    /**
     * Successful Response
     */
    200: MojangData;
};

export type GetMojangProfileV1PlayersMojangIdentifierGetResponse = GetMojangProfileV1PlayersMojangIdentifierGetResponses[keyof GetMojangProfileV1PlayersMojangIdentifierGetResponses];

export type GetPlayerCapesV1PlayersCapesUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/players/capes/{uuid}';
};

export type GetPlayerCapesV1PlayersCapesUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetPlayerCapesV1PlayersCapesUuidGetError = GetPlayerCapesV1PlayersCapesUuidGetErrors[keyof GetPlayerCapesV1PlayersCapesUuidGetErrors];

export type GetPlayerCapesV1PlayersCapesUuidGetResponses = {
    /**
     * Response Get Player Capes V1 Players Capes  Uuid  Get
     * Successful Response
     */
    200: Array<UserCapeData>;
};

export type GetPlayerCapesV1PlayersCapesUuidGetResponse = GetPlayerCapesV1PlayersCapesUuidGetResponses[keyof GetPlayerCapesV1PlayersCapesUuidGetResponses];

export type GetHypixelStatsV1PlayersHypixelUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/players/hypixel/{uuid}';
};

export type GetHypixelStatsV1PlayersHypixelUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetHypixelStatsV1PlayersHypixelUuidGetError = GetHypixelStatsV1PlayersHypixelUuidGetErrors[keyof GetHypixelStatsV1PlayersHypixelUuidGetErrors];

export type GetHypixelStatsV1PlayersHypixelUuidGetResponses = {
    /**
     * Successful Response
     */
    200: HypixelFullData;
};

export type GetHypixelStatsV1PlayersHypixelUuidGetResponse = GetHypixelStatsV1PlayersHypixelUuidGetResponses[keyof GetHypixelStatsV1PlayersHypixelUuidGetResponses];

export type GetHypixelGuildMembersV1HypixelGuildsIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: unknown;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Offset
         */
        offset?: number;
    };
    url: '/v1/hypixel/guilds/{id}';
};

export type GetHypixelGuildMembersV1HypixelGuildsIdGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetHypixelGuildMembersV1HypixelGuildsIdGetError = GetHypixelGuildMembersV1HypixelGuildsIdGetErrors[keyof GetHypixelGuildMembersV1HypixelGuildsIdGetErrors];

export type GetHypixelGuildMembersV1HypixelGuildsIdGetResponses = {
    /**
     * Response Get Hypixel Guild Members V1 Hypixel Guilds  Id  Get
     * Successful Response
     */
    200: Array<HypixelGuildMemberFull>;
};

export type GetHypixelGuildMembersV1HypixelGuildsIdGetResponse = GetHypixelGuildMembersV1HypixelGuildsIdGetResponses[keyof GetHypixelGuildMembersV1HypixelGuildsIdGetResponses];

export type GetPlayerOnlineStatusV1PlayersStatusUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/players/status/{uuid}';
};

export type GetPlayerOnlineStatusV1PlayersStatusUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetPlayerOnlineStatusV1PlayersStatusUuidGetError = GetPlayerOnlineStatusV1PlayersStatusUuidGetErrors[keyof GetPlayerOnlineStatusV1PlayersStatusUuidGetErrors];

export type GetPlayerOnlineStatusV1PlayersStatusUuidGetResponses = {
    /**
     * Successful Response
     */
    200: PlayerStatus;
};

export type GetPlayerOnlineStatusV1PlayersStatusUuidGetResponse = GetPlayerOnlineStatusV1PlayersStatusUuidGetResponses[keyof GetPlayerOnlineStatusV1PlayersStatusUuidGetResponses];

export type GetWynncraftStatsV1PlayersWynncraftUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/players/wynncraft/{uuid}';
};

export type GetWynncraftStatsV1PlayersWynncraftUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetWynncraftStatsV1PlayersWynncraftUuidGetError = GetWynncraftStatsV1PlayersWynncraftUuidGetErrors[keyof GetWynncraftStatsV1PlayersWynncraftUuidGetErrors];

export type GetWynncraftStatsV1PlayersWynncraftUuidGetResponses = {
    /**
     * Successful Response
     */
    200: WynncraftPlayerSummary;
};

export type GetWynncraftStatsV1PlayersWynncraftUuidGetResponse = GetWynncraftStatsV1PlayersWynncraftUuidGetResponses[keyof GetWynncraftStatsV1PlayersWynncraftUuidGetResponses];

export type GetWynncraftGuildDataV1WynncraftGuildsPrefixGetData = {
    body?: never;
    path: {
        /**
         * Prefix
         */
        prefix: unknown;
    };
    query?: never;
    url: '/v1/wynncraft/guilds/{prefix}';
};

export type GetWynncraftGuildDataV1WynncraftGuildsPrefixGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetWynncraftGuildDataV1WynncraftGuildsPrefixGetError = GetWynncraftGuildDataV1WynncraftGuildsPrefixGetErrors[keyof GetWynncraftGuildDataV1WynncraftGuildsPrefixGetErrors];

export type GetWynncraftGuildDataV1WynncraftGuildsPrefixGetResponses = {
    /**
     * Successful Response
     */
    200: WynncraftGuildInfo;
};

export type GetWynncraftGuildDataV1WynncraftGuildsPrefixGetResponse = GetWynncraftGuildDataV1WynncraftGuildsPrefixGetResponses[keyof GetWynncraftGuildDataV1WynncraftGuildsPrefixGetResponses];

export type GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
        /**
         * Character Uuid
         */
        character_uuid: string;
    };
    query: {
        /**
         * Class
         */
        class: 'warrior' | 'mage' | 'archer' | 'assassin' | 'shaman';
    };
    url: '/v1/players/wynncraft/{uuid}/characters/{character_uuid}/ability-tree';
};

export type GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetError = GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetErrors[keyof GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetErrors];

export type GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetResponses = {
    /**
     * Response Get Wynncraft Character Ability Tree V1 Players Wynncraft  Uuid  Characters  Character Uuid  Ability Tree Get
     * Successful Response
     */
    200: Array<AbilityTreePage>;
};

export type GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetResponse = GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetResponses[keyof GetWynncraftCharacterAbilityTreeV1PlayersWynncraftUuidCharactersCharacterUuidAbilityTreeGetResponses];

export type GetDonutSmpStatsV1PlayersDonutsmpUsernameGetData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/v1/players/donutsmp/{username}';
};

export type GetDonutSmpStatsV1PlayersDonutsmpUsernameGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetDonutSmpStatsV1PlayersDonutsmpUsernameGetError = GetDonutSmpStatsV1PlayersDonutsmpUsernameGetErrors[keyof GetDonutSmpStatsV1PlayersDonutsmpUsernameGetErrors];

export type GetDonutSmpStatsV1PlayersDonutsmpUsernameGetResponses = {
    /**
     * Successful Response
     */
    200: DonutPlayerStats;
};

export type GetDonutSmpStatsV1PlayersDonutsmpUsernameGetResponse = GetDonutSmpStatsV1PlayersDonutsmpUsernameGetResponses[keyof GetDonutSmpStatsV1PlayersDonutsmpUsernameGetResponses];

export type GetMccIslandStatsV1PlayersMccislandUuidGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/players/mccisland/{uuid}';
};

export type GetMccIslandStatsV1PlayersMccislandUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetMccIslandStatsV1PlayersMccislandUuidGetError = GetMccIslandStatsV1PlayersMccislandUuidGetErrors[keyof GetMccIslandStatsV1PlayersMccislandUuidGetErrors];

export type GetMccIslandStatsV1PlayersMccislandUuidGetResponses = {
    /**
     * Successful Response
     */
    200: McciPlayer;
};

export type GetMccIslandStatsV1PlayersMccislandUuidGetResponse = GetMccIslandStatsV1PlayersMccislandUuidGetResponses[keyof GetMccIslandStatsV1PlayersMccislandUuidGetResponses];

export type GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetData = {
    body?: never;
    path: {
        /**
         * Metric Key
         */
        metric_key: string;
        /**
         * Player Uuid
         */
        player_uuid: string;
    };
    query?: never;
    url: '/v1/metrics/{metric_key}/distribution/{player_uuid}';
};

export type GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponse;
    /**
     * Forbidden
     */
    403: ErrorResponse;
    /**
     * Not Found
     */
    404: ErrorResponse;
    /**
     * Unprocessable Entity
     */
    422: ErrorResponse;
    /**
     * Too Many Requests
     */
    429: ErrorResponse;
    /**
     * Internal Server Error
     */
    500: ErrorResponse;
    /**
     * Upstream Error
     */
    502: ErrorResponse;
    /**
     * Upstream Timeout
     */
    504: ErrorResponse;
};

export type GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetError = GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetErrors[keyof GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetErrors];

export type GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetResponses = {
    /**
     * Successful Response
     */
    200: HistogramData;
};

export type GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetResponse = GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetResponses[keyof GetMetricDistributionV1MetricsMetricKeyDistributionPlayerUuidGetResponses];

export type TrackPlayerOnlineStatusV1TrackerUuidStatusGetData = {
    body?: never;
    path: {
        /**
         * Uuid
         */
        uuid: string;
    };
    query?: never;
    url: '/v1/tracker/{uuid}/status';
};

export type TrackPlayerOnlineStatusV1TrackerUuidStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TrackPlayerOnlineStatusV1TrackerUuidStatusGetError = TrackPlayerOnlineStatusV1TrackerUuidStatusGetErrors[keyof TrackPlayerOnlineStatusV1TrackerUuidStatusGetErrors];

export type TrackPlayerOnlineStatusV1TrackerUuidStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};
